// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $account_index from "./routes/account/index.tsx";
import * as $account_manage from "./routes/account/manage.ts";
import * as $account_upgrade from "./routes/account/upgrade.ts";
import * as $api_me_assets from "./routes/api/me/assets.ts";
import * as $api_me_votes from "./routes/api/me/votes.ts";
import * as $api_retirement_plan from "./routes/api/retirement-plan.ts";
import * as $api_stripe_webhooks from "./routes/api/stripe-webhooks.ts";
import * as $api_users_login_assets from "./routes/api/users/[login]/assets.ts";
import * as $api_users_login_index from "./routes/api/users/[login]/index.ts";
import * as $api_users_index from "./routes/api/users/index.ts";
import * as $api_yf_chart from "./routes/api/yf/chart.ts";
import * as $api_yf_quote from "./routes/api/yf/quote.ts";
import * as $api_yf_search from "./routes/api/yf/search.ts";
import * as $assets from "./routes/assets.tsx";
import * as $assets_gold from "./routes/assets/gold.tsx";
import * as $assets_stocks from "./routes/assets/stocks.tsx";
import * as $dashboard_growth from "./routes/dashboard/growth.tsx";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $dashboard_plan from "./routes/dashboard/plan.tsx";
import * as $dashboard_stats from "./routes/dashboard/stats.tsx";
import * as $dashboard_users from "./routes/dashboard/users.tsx";
import * as $index from "./routes/index.tsx";
import * as $plan from "./routes/plan.tsx";
import * as $pricing from "./routes/pricing.tsx";
import * as $submit from "./routes/submit.tsx";
import * as $users_login_ from "./routes/users/[login].tsx";
import * as $welcome from "./routes/welcome.tsx";
import * as $AssetDonut from "./islands/AssetDonut.tsx";
import * as $AssetForm from "./islands/AssetForm.tsx";
import * as $AssetViewer from "./islands/AssetViewer.tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $GoldChart from "./islands/GoldChart.tsx";
import * as $GrowthTable from "./islands/GrowthTable.tsx";
import * as $ItemsList from "./islands/ItemsList.tsx";
import * as $RetirementPlan from "./islands/RetirementPlan.tsx";
import * as $RetirementProgress from "./islands/RetirementProgress.tsx";
import * as $StockChart from "./islands/StockChart.tsx";
import * as $UsersTable from "./islands/UsersTable.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/account/index.tsx": $account_index,
    "./routes/account/manage.ts": $account_manage,
    "./routes/account/upgrade.ts": $account_upgrade,
    "./routes/api/me/assets.ts": $api_me_assets,
    "./routes/api/me/votes.ts": $api_me_votes,
    "./routes/api/retirement-plan.ts": $api_retirement_plan,
    "./routes/api/stripe-webhooks.ts": $api_stripe_webhooks,
    "./routes/api/users/[login]/assets.ts": $api_users_login_assets,
    "./routes/api/users/[login]/index.ts": $api_users_login_index,
    "./routes/api/users/index.ts": $api_users_index,
    "./routes/api/yf/chart.ts": $api_yf_chart,
    "./routes/api/yf/quote.ts": $api_yf_quote,
    "./routes/api/yf/search.ts": $api_yf_search,
    "./routes/assets.tsx": $assets,
    "./routes/assets/gold.tsx": $assets_gold,
    "./routes/assets/stocks.tsx": $assets_stocks,
    "./routes/dashboard/growth.tsx": $dashboard_growth,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/dashboard/plan.tsx": $dashboard_plan,
    "./routes/dashboard/stats.tsx": $dashboard_stats,
    "./routes/dashboard/users.tsx": $dashboard_users,
    "./routes/index.tsx": $index,
    "./routes/plan.tsx": $plan,
    "./routes/pricing.tsx": $pricing,
    "./routes/submit.tsx": $submit,
    "./routes/users/[login].tsx": $users_login_,
    "./routes/welcome.tsx": $welcome,
  },
  islands: {
    "./islands/AssetDonut.tsx": $AssetDonut,
    "./islands/AssetForm.tsx": $AssetForm,
    "./islands/AssetViewer.tsx": $AssetViewer,
    "./islands/Chart.tsx": $Chart,
    "./islands/GoldChart.tsx": $GoldChart,
    "./islands/GrowthTable.tsx": $GrowthTable,
    "./islands/ItemsList.tsx": $ItemsList,
    "./islands/RetirementPlan.tsx": $RetirementPlan,
    "./islands/RetirementProgress.tsx": $RetirementProgress,
    "./islands/StockChart.tsx": $StockChart,
    "./islands/UsersTable.tsx": $UsersTable,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
